### ISSUE TITLE
Getting the test to work

### ISSUE THREAD

**Issue by bram-dingelstad** [kyperbelt/GDYarn#1]
Hey @kyperbelt! 

First of all, amazing project that I think will add a lot to the Godot ecosystem so good job!
I am however running into some issues. When I run this using 3.2.2, it doesn't work out of the box and keeps generating errors around cyclical references. Any idea what causes this or how I can get it back to a working state?

Thanks in advance!

**Comment by A1asd** [comment]
Same for me. On attempting to run test.tsn or testdisplay.tscn i get `Parsing Error: The identifier "YarnGlobals" isn't declared in the current scope.` I guess i have to load YarnGlobals in the autoloader somewhere? I hope my problem is related to this issue.

**Comment by bram-dingelstad** [comment]
I got it to work eventually by just eliminating each error after another. It seems like this thing is riddled with race conditions and other issues 😅 
I'll try and see if I can fork it and perhaps bring about some improvements!

**Comment by kyperbelt** [comment]
> I got it to work eventually by just eliminating each error after another. It seems like this thing is riddled with race conditions and other issues sweat_smile I'll try and see if I can fork it and perhaps bring about some improvements!

Hello Bram, sorry that this is one year after your initial posting. 

I just recently got back to working on this project. The code can definitely improve (any help is appreciated), and I hope that with the latest update, I fixed some if not all of the cyclic issues. 

I added a compile button to the yarn_runner to save the programs to file as it was not working with the game exported.

Right now my main focus will be getting feature parity with the c# version and fixing some of the spaghetti along the way. 


I read the suggestions in your fork and I really appreciate them.

**Comment by bram-dingelstad** [comment]
Hey kyperbelt!

I’m already using and testing the code and plugin in two different projects at the time of writing. Some changes I made are against the spec of the original YarnSpinner, so I think I’ll need to revert them.

I’ll try to get those changes back to my fork sometime soon.

I would love to continue working on this project and get some eyes on this plugin, as I think that it can really make Godot a good engine for people wanting to make more complex dialogue-based games.

Thank you for messaging back! Let me know if you wanna discuss more things on the project or assign me some stuff. Would love to help out 😊

**Comment by kyperbelt** [comment]
I agree that the plugin will need more visibility in order to grow. 

I am in the process of figuring out what needs to be done next (depending on how far gdyarn is lagging behind C#YarnSpinner). 

I am going to put my focus on fixing the dialogueDisplay script and the way the yarn_runner works. I really like your idea of using signals to process the dialogue output so that is definitely something that will be implemented. 

I want to work on spicing up the asset download page with some images, a video, and feature information. 
I definitely need to add better examples, and to make the README have more relevant information (right now, it's kind of half notes to myself haha) about how to get started with using the plugin and expanding it.

I would also like to create some sort of contribution and style guide.

Once I get all of that sorted ill start to compartmentalize and post tasks in the issues tab for anyone to tackle.
